name: Simple Test Workflow

on:
  push:
    branches:
      - master

jobs:
  simple-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Say Hello
        run: |
          echo "✅ Hello, GitHub Actions is working!"
          echo "📦 Repo: $GITHUB_REPOSITORY"
          echo "🕒 Commit: $GITHUB_SHA"
